name: deploy test

on:
  workflow_dispatch:
  ###############################################################
  # Динамический анализ (DAST)
  dast:
    runs-on: ubuntu-24.04    
    steps:
      # Скачивание кода
      - name: Checkout Code
        uses: actions/checkout@v7

      # После многочисленных экспериментов и чтения исходников, пришел к такому решению, чтобы не использовать kubernetes.
      # Вручную создается docker-compose.yml и запускается через docker compose.
      # Создается минимально необходимый список из служб, чтобы заработал frontend
      # Именно frontend и тестируется с помощью owasp zap

      - name: Generate Docker Compose File
        run: |
          cat <<EOF > docker-compose.yml
          version: '3.8'
          services:
            redis-cart:
              image: redis:7-alpine
              ports:
                - "6379"

            productcatalogservice:
              build:
                context: ./src/productcatalogservice
              ports:
                - "3550:3550"

            currencyservice:
              build:
                context: ./src/currencyservice
              ports:
                - "7000:7000"

            cartservice:
              build:
                context: ./src/cartservice/src
              ports:
                - "7070:7070"
              environment:
                - REDIS_ADDR=redis-cart:6379
              depends_on:
                - redis-cart

            frontend:
              build:
                context: ./src/frontend
              ports:
                - "8080:8080"
              environment:
                - PORT=8080
                - ENV_PLATFORM=local
                # Перенаправляем обязательные gRPC сервисы на реальные контейнеры
                - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
                - CURRENCY_SERVICE_ADDR=currencyservice:7000
                - CART_SERVICE_ADDR=cartservice:7070
                # Остальные второстепенные сервисы пускаем на любой живой порт, чтобы не было паники
                - RECOMMENDATION_SERVICE_ADDR=productcatalogservice:3550
                - SHIPPING_SERVICE_ADDR=productcatalogservice:3550
                - CHECKOUT_SERVICE_ADDR=productcatalogservice:3550
                - AD_SERVICE_ADDR=productcatalogservice:3550
                - SHOPPING_ASSISTANT_SERVICE_ADDR=productcatalogservice:3550
              depends_on:
                - productcatalogservice
                - currencyservice
                - cartservice
          EOF
      # Сборка и запуск докер образов с помощью docker compose
      - name: Start frontend
        run: |
          docker compose up -d --build
          echo "Waiting for frontend"
          sleep 15
