name: Online Boutique DevSecOps Pipeline 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  # 1. Матричная сборка для валидации Dockerfile (как и требовалось)
  build-services:
    name: Build Service
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        service: [
          "adservice",
          "checkoutservice",
          "currencyservice",
          "emailservice",
          "frontend",
          "paymentservice",
          "productcatalogservice",
          "recommendationservice",
          "shippingservice"
        ]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker Image (Dry-Run)
        uses: docker/build-push-action@v7
        with:
          context: ./src/${{ matrix.service }}
          push: false
          tags: boutique-${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Docker Image (Dry-Run)
        uses: docker/build-push-action@v7
        with:
          context: ./src/cartservice/src
          push: false
          tags: boutique-cartservice:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # 2. Развертывание в локальный K8s (Kind) и DAST-сканирование
  dast:
    name: OWASP ZAP DAST Analysis
    runs-on: ubuntu-24.04
    # Запускаем после того, как убедились, что все сервисы собираются
    needs: build-services 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      # Динамически создаем docker-compose.yml для тестирования фронтенда
      - name: Generate Docker Compose File
        run: |
          cat <<EOF > docker-compose.yml
          version: '3.8'
          services:
            redis-cart:
              image: redis:7-alpine
              ports:
                - "6379"

            productcatalogservice:
              build:
                context: ./src/productcatalogservice
              ports:
                - "3550:3550"

            currencyservice:
              build:
                context: ./src/currencyservice
              ports:
                - "7000:7000"

            cartservice:
              build:
                context: ./src/cartservice/src
              ports:
                - "7070:7070"
              environment:
                - REDIS_ADDR=redis-cart:6379
              depends_on:
                - redis-cart

            frontend:
              build:
                context: ./src/frontend
              ports:
                - "8080:8080"
              environment:
                - PORT=8080
                - ENV_PLATFORM=local
                # Перенаправляем обязательные gRPC сервисы на реальные контейнеры
                - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
                - CURRENCY_SERVICE_ADDR=currencyservice:7000
                - CART_SERVICE_ADDR=cartservice:7070
                # Остальные второстепенные сервисы пускаем на любой живой порт, чтобы не было паники
                - RECOMMENDATION_SERVICE_ADDR=productcatalogservice:3550
                - SHIPPING_SERVICE_ADDR=productcatalogservice:3550
                - CHECKOUT_SERVICE_ADDR=productcatalogservice:3550
                - AD_SERVICE_ADDR=productcatalogservice:3550
              depends_on:
                - productcatalogservice
                - currencyservice
                - cartservice
          EOF
      # Поднимаем сгенерированный Docker Compose
      - name: Start Frontend via Docker Compose
        run: |
          docker compose up -d --build
          echo "Waiting for frontend to spin up..."
          sleep 15

      # Проверяем, отвечает ли порт приложения
      - name: Verify Frontend Availability
        run: |
          curl -I http://localhost:8080 || exit 1

      # Локальный DAST-анализ с помощью OWASP ZAP
      - name: OWASP ZAP Baseline Scan (DAST)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8080'
          fail_action: false
          cmd_options: '-a'

      # Очистка ресурсов
      - name: Stop Infrastructure
        if: always()
        run: docker compose down        

        
       # Блокировка
      - name: Block
        run: |
          exit 1            

  ###############################################################
  # Поиск секретов
  secrets:
    runs-on: ubuntu-24.04
    needs: dast
    steps:
      # скачиваем код с github на сервер для проверки (В runner)
      - name: Checkout full history code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # вся история

      # Проверка репозитория на секреты. Gitleaks
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Проверка репозитория на секреты. Trivy
      - name: Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scanners: 'secret'
          format: 'sarif'
          output: 'trivy-secrets-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-secrets-results.sarif'
          category: 'trivy-secrets'
          
      # Сохранение отчета в CI Артефакты
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: trivy-secrets-results
          path: trivy-secrets-results.sarif
          retention-days: 7          

      # Проверка конфигураций
      - name: Audit Kubernetes & Helm Configurations
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          format: 'sarif'
          output: 'trivy-iac-results.sarif'

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload IaC Misconfigurations to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-iac-results.sarif'
          category: 'trivy-iac'

      # Сохранение отчета в CI Артефакты
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: trivy-iac-results
          path: trivy-iac-results.sarif
          retention-days: 7    
          
  ###############################################################
  # Статический анализ
  sast:
    runs-on: ubuntu-24.04
    needs: secrets
    steps:
      # скачиваем код с github на сервер для проверки (В runner)
      - name: Checkout code
        uses: actions/checkout@v7

      # Сканирование исходного кода. Trivy.
      - name: SAST (Trivy)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scanners: 'vuln,misconfig'
          format: 'sarif'
          output: 'trivy-sast-results.sarif'
          exit-code: '0'

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload SAST Results (Trivy)
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-sast-results.sarif'
          category: 'trivy-sast-results'

      # Сохранение отчета в CI Артефакты (Trivy)
      - name: Upload SAST Results (Trivy)
        uses: actions/upload-artifact@v7
        with:
          name: trivy-sast-results
          path: trivy-sast-results.sarif
          retention-days: 7

      # Сканирование исходного кода. Semgrep.
      - name: SAST (Semgrep)
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep \
            semgrep scan --config=auto --sarif-output=/src/semgrep-sast-results.sarif

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload SAST Results (Trivy)
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'semgrep-sast-results.sarif'
          category: 'semgrep-sast-results'

      # Сохранение отчета в CI Артефакты (Semgrep)
      - name: Upload SAST Results (Semgrep)
        uses: actions/upload-artifact@v7
        with:
          name: semgrep-sast-results
          path: semgrep-sast-results.sarif
          retention-days: 7

  ###############################################################
  # Сборка и сканирование контейнеров
  build_scan_images:
    needs: sast
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        service: [
        #"cartservice",
          "adservice", "checkoutservice", "currencyservice",
          "emailservice", "frontend", "loadgenerator", "paymentservice",
          "productcatalogservice", "recommendationservice", "shippingservice"
        ]    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      # Сборка Docker-образа
      - name: Build Docker Image
        run: |
          cd src/frontend/
          docker build -t ${{ matrix.service }}:${{ github.sha }} .

      # Сканирование уязвимостей в контейнере
      - name: Container Scan (Trivy)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{ matrix.service }}:${{ github.sha }}'
          scan-type: 'image'
          format: 'sarif'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'          
          output: '${{ matrix.service }}-trivy-image-results.sarif'
          exit-code: '0'

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload Image Results (Trivy)
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: '${{ matrix.service }}-trivy-image-results.sarif'
          category: '${{ matrix.service }}-trivy-image'

      # Сохранение отчета в CI Артефакты
      - name: Upload Image Results (Trivy)
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.service }}-trivy-image-results
          path: ${{ matrix.service }}-trivy-image-results.sarif
          retention-days: 7          
          
      # Проверка Dockerfile на best practices
      - name: Lint Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v3.5.0
        with:
          dockerfile: src/${{ matrix.service }}/Dockerfile
          format: sarif
          output-file: hadolint-${{ matrix.service }}.sarif
          no-fail: true

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload Results (Hadolint)
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'hadolint-${{ matrix.service }}.sarif'
          category: 'hadolint-${{ matrix.service }}'

      # Сохранение отчета в CI Артефакты
      - name: Upload Results (Hadolint)
        uses: actions/upload-artifact@v7
        with:
          name: hadolint-${{ matrix.service }}
          path: hadolint-${{ matrix.service }}.sarif
          retention-days: 7                    
  ###############################################################
  # Блокировка релиза
  security_gateway:
    runs-on: ubuntu-24.04
    needs: [secrets, sast, build_scan_images, dast]
    if: always()
    steps:
      - name: Download Artifact (Trivy)
        uses: actions/download-artifact@v8
        with:
          name: trivy-sast-results
          path: ./reports

      - name: Download Artifact (Semgrep)
        uses: actions/download-artifact@v8
        with:
          name: semgrep-sast-results
          path: ./reports

      - name: Download Secrets (Trivy)
        uses: actions/download-artifact@v8
        with:
          name: trivy-secrets-results
          path: ./reports

      - name: Download IaC (Trivy)
        uses: actions/download-artifact@v8
        with:
          name: trivy-iac-results
          path: ./reports

      # Проверка на наличие уязвимостей
      - name: Verify
        run: |
          echo "Проверка критических уязвимостей"
          
          # Проверяем файлы отчетов SAST на наличие критических уязвимостей
          if grep -q "CRITICAL" ./reports/trivy-sast-results.sarif; then
            echo "GATE_STATUS=FAILED" >> $GITHUB_ENV
            echo "::error::Релиз заблокирован! Обнаружены критические уязвимости (CRITICAL) в коде или зависимостях. (Trivy)"
          else
            echo "GATE_STATUS=PASSED" >> $GITHUB_ENV
          fi

          if grep -q "CRITICAL" ./reports/semgrep-sast-results.sarif; then
            echo "GATE_STATUS=FAILED" >> $GITHUB_ENV
            echo "::error::Релиз заблокирован! Обнаружены критические уязвимости (CRITICAL) в коде или зависимостях. (Semgrep)"
          else
            echo "GATE_STATUS=PASSED" >> $GITHUB_ENV
          fi

          if grep -q "CRITICAL" ./reports/trivy-secrets-results.sarif; then
            echo "GATE_STATUS=FAILED" >> $GITHUB_ENV
            echo "::error::Релиз заблокирован! Обнаружены секреты в репозитории. (Trivy)"
          else
            echo "GATE_STATUS=PASSED" >> $GITHUB_ENV
          fi

          if grep -q "CRITICAL" ./reports/trivy-iac-results.sarif; then
            echo "GATE_STATUS=FAILED" >> $GITHUB_ENV
            echo "::error::Релиз заблокирован! Обнаружены проблемы в конфигурации. (Trivy)"
          else
            echo "GATE_STATUS=PASSED" >> $GITHUB_ENV
          fi

      - name: Create report
        if: env.GATE_STATUS == 'FAILED'
        run: |
          echo "### В резкльтате проверки кода были найдены критические уязвимости" > summary.md
          echo "- Время обновления: %NOW%" >> summary.md
          echo "Исправить код помогут выгруженные артефакты (логи) и гугл. " > comments.md
          
      # Комментарии в PR
      - name: Update
        if: env.GATE_STATUS == 'FAILED'
        uses: mshick/add-pr-comment@v3
        with:
          message-id: qa-summary-report
          message-path: summary.md
          attach-path: comments.md
          refresh-message-position: true
           
     # Блокировка
      - name: Block
        if: env.GATE_STATUS == 'FAILED'
        run: |
          echo "Остановка пайплайна из-за критических уязвимостей"
          exit 1            
