name: Online Boutique DevSecOps Pipeline 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write

env:
  IMAGE_NAME: "online-boutique"

jobs:
  ###############################################################
  # Сборка и сканирование контейнеров
  dact:
#    needs: sast
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        service: [
          "adservice", "cartservice", "checkoutservice", "currencyservice",
          "emailservice", "frontend", "loadgenerator", "paymentservice",
          "productcatalogservice", "recommendationservice", "shippingservice"
        ]    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      # Проверка Dockerfile на best practices
#      - name: Lint Dockerfile (Hadolint)
#        uses: hadolint/hadolint-action@v3.5.0
#        with:
#          dockerfile: src/${{ matrix.service }}/Dockerfile
#          format: sarif
#          output-file: hadolint-${{ matrix.service }}.sarif
#          no-fail: true

#      - name: Upload Results (Hadolint)
#        uses: github/codeql-action/upload-sarif@v4
#        if: always()
#        with:
#          sarif_file: 'hadolint-${{ matrix.service }}.sarif'
#          category: 'hadolint-${{ matrix.service }}'
                    
      # Сборка Docker-образа
      - name: buildx
        uses: docker/setup-buildx-action@v4

      - name: Build adservice Service
        uses: docker/build-push-action@v7
        with:
          context: ./src/${{ matrix.service }}
          file: ./src/${{ matrix.service }}/Dockerfile
          tags: boutique-${{ matrix.service }}:latest
          outputs: type=docker
          push: false
          load: true
          
      # Поднимаем приложение. Для DAST нам нужен работающий Frontend и минимальный бэкенд.
      # Используем официальный docker-compose.yaml из репозитория Google Online Boutique.
      - name: Start Online Boutique Locally
        run: |
          docker-compose -f ./src/docker-compose.yml up -d
          echo "Waiting for frontend to be ready..."
          # Ждем, пока веб-интерфейс начнет отвечать (порт 8080 по умолчанию)
          timeout 60s sh -c 'until curl -sf http://localhost:8080; do sleep 2; done'

      # Запуск OWASP ZAP в режиме Baseline Scan (быстрый поиск явных уязвимостей без глубокого спайдеринга)
      # Запуск происходит локально в Docker-контейнере, сеть "host" позволяет видеть localhost раннера.
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8080/'
          rules_file_name: '.zap/rules.tsv' # Файл исключений (опционально)
          cmd_options: '-a' # Включает alpha-правила сканирования
          fail_action: false # Не ронять пайплайн сразу, чтобы успеть сохранить артефакты (для DevSecOps важно видеть отчет)
      
      # Остановка контейнеров после завершения тестов
      - name: Stop Containers
        if: always()
        run: docker-compose -f ./src/docker-compose.yml down
          
#      - name: Build image
 #       run: |
 #         echo "Building Docker image ${{ matrix.service }}..."          
 #         docker build -t boutique-${{ matrix.service }}:local ./src/${{ matrix.service }}
            
#      - name: Start
#        run: |
#          docker run -d boutique-${{ matrix.service }}:local
#          sleep 10
#          mkdir -p ${{ github.workspace }}/zap-results
#          chmod 777 ${{ github.workspace }}/zap-results                   

      # запускаем сканер
#      - name: OWASP ZAP
#        uses: zaproxy/action-baseline@v0.15.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          target: 'http://localhost:8080'
#          fail_action: false
#          cmd_options: '-a -J zap_report.json'
#          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'

#      - name: Convert to sarif
#        uses: SvanBoxel/zaproxy-to-ghas@v1.0.2        
#        continue-on-error: true
#        with:
#          zap_json_report: 'zap_report.json'
          
#      - name: Upload SARIF file to GitHub Security Tab
#        uses: github/codeql-action/upload-sarif@v4
#        if: always()
#        with:
#          sarif_file: results.sarif
#          category: zap-dast-${{ matrix.service }}

#      # чистим за собой
#      - name: Cleanup Containers
#        if: always()
#        run: |
#          docker stop test-app || true
 #         docker rm test-app || true
 #         docker network rm dast-net || true
                   
#        run: |
#          cd src/frontend/
#          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

      # Сканирование уязвимостей в контейнере
#      - name: Container Scan (Trivy)
#        uses: aquasecurity/trivy-action@v0.36.0
#        with:
#          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
#          scan-type: 'image'
#          format: 'sarif'
#          output: 'image-trivy-report.sarif'
#          ignore-unfixed: true
#          severity: 'CRITICAL,HIGH'
          
#      # Выгрузка результатов в GitHub Code Scanning
#      - name: Upload Image Scan
#        uses: github/codeql-action/upload-sarif@v4
#        if: always()
#        with:
#          sarif_file: 'image-trivy-report.sarif'
#          category: 'trivy-image'

      # Сохранение отчета в CI Артефакты (Trivy)
#      - name: Upload Scan Image Result
#        uses: actions/upload-artifact@v7
#        with:
#          name: image-trivy-report
#          path: image-trivy-report.sarif
#          retention-days: 7

      - name: Block
        run: |
          exit 1            
  
  
  ###############################################################
  # Поиск секретов
  secrets:
    runs-on: ubuntu-24.04
    steps:
      - name: Block
        run: |
          exit 1            

      # скачиваем код с github на сервер для проверки (В runner)
      - name: Checkout full history code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # вся история

      # Проверка репозитория на секреты. Gitleaks
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Проверка репозитория на секреты. Trivy
      - name: Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scanners: 'secret'
          format: 'sarif'
          output: 'trivy-secrets-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-secrets-results.sarif'
          category: 'trivy-secrets'
          
      # Сохранение отчета в CI Артефакты
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: trivy-secrets-results
          path: trivy-secrets-results.sarif
          retention-days: 7          

      # Проверка конфигураций
      - name: Audit Kubernetes & Helm Configurations
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          format: 'sarif'
          output: 'trivy-iac-results.sarif'

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload IaC Misconfigurations to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-iac-results.sarif'
          category: 'trivy-iac'

      # Сохранение отчета в CI Артефакты
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: trivy-iac-results
          path: trivy-iac-results.sarif
          retention-days: 7    
          
  ###############################################################
  # Статический анализ
  sast:
    runs-on: ubuntu-24.04
    needs: secrets
    steps:
      # скачиваем код с github на сервер для проверки (В runner)
      - name: Checkout code
        uses: actions/checkout@v7

      # Сканирование исходного кода. Trivy.
      - name: SAST (Trivy)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scanners: 'vuln,misconfig'
          format: 'sarif'
          output: 'sast-results.sarif'
          exit-code: '0'

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload SAST Results (Trivy)
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'sast-results.sarif'
          category: 'trivy-sast'

      # Сохранение отчета в CI Артефакты (Trivy)
      - name: Upload SAST Results (Trivy)
        uses: actions/upload-artifact@v7
        with:
          name: sast-trivy-report
          path: sast-results.sarif
          retention-days: 7

      # Сканирование исходного кода. Semgrep.
      - name: SAST (Semgrep)
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep \
            semgrep scan --config=auto --sarif-output=/src/semgrep-sast-report.sarif

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload SAST Results (Trivy)
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'semgrep-sast-report.sarif'
          category: 'semgrep-sast'

      # Сохранение отчета в CI Артефакты (Semgrep)
      - name: Upload SAST Results (Semgrep)
        uses: actions/upload-artifact@v7
        with:
          name: sast-semgrep-report
          path: semgrep-sast-report.sarif
          retention-days: 7

  ###############################################################
  # Блокировка релиза
  security_gateway:
    runs-on: ubuntu-24.04
    needs: [secrets, sast, dact]
    if: always()
    steps:
      - name: Download Artifact (Trivy)
        uses: actions/download-artifact@v8
        with:
          name: sast-trivy-report
          path: ./reports

      - name: Download Artifact (Semgrep)
        uses: actions/download-artifact@v8
        with:
          name: sast-semgrep-report
          path: ./reports

      - name: Download Secrets (Trivy)
        uses: actions/download-artifact@v8
        with:
          name: trivy-secrets-results
          path: ./reports

      - name: Download IaC (Trivy)
        uses: actions/download-artifact@v8
        with:
          name: trivy-iac-results
          path: ./reports

      # Проверка на наличие уязвимостей
      - name: Verify
        run: |
          echo "Проверка критических уязвимостей"
          
          # Проверяем файлы отчетов SAST на наличие критических уязвимостей
          if grep -q "CRITICAL" ./reports/sast-results.sarif; then
            echo "GATE_STATUS=FAILED" >> $GITHUB_ENV
            echo "::error::Релиз заблокирован! Обнаружены критические уязвимости (CRITICAL) в коде или зависимостях. (Trivy)"
          else
            echo "GATE_STATUS=PASSED" >> $GITHUB_ENV
          fi

          if grep -q "CRITICAL" ./reports/semgrep-sast-report.sarif; then
            echo "GATE_STATUS=FAILED" >> $GITHUB_ENV
            echo "::error::Релиз заблокирован! Обнаружены критические уязвимости (CRITICAL) в коде или зависимостях. (Semgrep)"
          else
            echo "GATE_STATUS=PASSED" >> $GITHUB_ENV
          fi

          if grep -q "CRITICAL" ./reports/trivy-secrets-results.sarif; then
            echo "GATE_STATUS=FAILED" >> $GITHUB_ENV
            echo "::error::Релиз заблокирован! Обнаружены секреты в репозитории. (Trivy)"
          else
            echo "GATE_STATUS=PASSED" >> $GITHUB_ENV
          fi

          if grep -q "CRITICAL" ./reports/trivy-iac-results.sarif; then
            echo "GATE_STATUS=FAILED" >> $GITHUB_ENV
            echo "::error::Релиз заблокирован! Обнаружены проблемы в конфигурации. (Trivy)"
          else
            echo "GATE_STATUS=PASSED" >> $GITHUB_ENV
          fi

      - name: Create report
        if: env.GATE_STATUS == 'FAILED'
        run: |
          echo "### В резкльтате проверки кода были найдены критические уязвимости" > summary.md
          echo "- Время обновления: %NOW%" >> summary.md
          echo "Исправить код помогут выгруженные артефакты (логи) и гугл. " > comments.md
          
      # Комментарии в PR
      - name: Update
        if: env.GATE_STATUS == 'FAILED'
        uses: mshick/add-pr-comment@v3
        with:
          message-id: qa-summary-report
          message-path: summary.md
          attach-path: comments.md
          refresh-message-position: true
           
     # Блокировка
      - name: Block
        if: env.GATE_STATUS == 'FAILED'
        run: |
          echo "Остановка пайплайна из-за критических уязвимостей"
          exit 1            
