name: Online Boutique DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write

env:
  IMAGE_NAME: "online-boutique-frontend"
  # URL вашего сервера в Yandex Cloud для DAST-тестов
  TARGET_URL: "http://your-vps-ip:80"

jobs:
  ###############################################################
  # Поиск секретов
  secrets:
    runs-on: ubuntu-latest
    steps:
      # скачиваем код с github на сервер для проверки (В runner)
      - name: Checkout full history code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # вся история

      # Проверка репозитория на секреты. Gitleaks
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Проверка репозитория на секреты. Trivy
      - name: Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scanners: 'secret'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      # Проверка конфигураций
      - name: Audit Kubernetes & Helm Configurations
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          exit-code: '0'
          format: 'sarif'
          output: 'iac-results.sarif'

      # Выгрузка результатов в GitHub Security Tab
      - name: Upload IaC Misconfigurations to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'iac-results.sarif'
          category: 'trivy-iac'
  ###############################################################
  # Статический анализ (SAST)
  sast:
    runs-on: ubuntu-latest
    needs: secrets
    steps:
      # скачиваем код с github на сервер для проверки (В runner)
      - name: Checkout code
        uses: actions/checkout@v7

      # Сканирование исходного кода. Trivy.
      - name: SAST (Trivy)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scanners: 'vuln,misconfig'
          format: 'sarif'
          output: 'sast-results.sarif'
          exit-code: '0'

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload SAST Results (Trivy)
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'sast-results.sarif'
          category: 'trivy-sast'

      # Сохранение отчета в CI Артефакты (Trivy)
      - name: Upload SAST Results (Trivy)
        uses: actions/upload-artifact@v7
        with:
          name: sast-trivy-report
          path: sast-results.sarif
          retention-days: 7

      # Сканирование исходного кода. Semgrep.
      - name: SAST (Semgrep)
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep \
            semgrep scan --config=auto --sarif-output=/src/semgrep-sast-report.sarif

      # Сохранение отчета в CI Артефакты (Semgrep)
      - name: Upload SAST Results (Semgrep)
        uses: actions/upload-artifact@v7
        with:
          name: sast-semgrep-report
          path: |
            semgrep-sast-report.sarif
          retention-days: 7
