name: test Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  test1:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: step1
        run: |
          echo "test1.step 1"
          echo "GATE_STATUS=FAILED" >> $GITHUB_ENV
      - name: step2
        run: |
          echo "test1.step 2"
          echo "GATE_STATUS: ${{ env.GATE_STATUS }}"            
  test2:
    runs-on: ubuntu-latest    
    needs: test1
    if: always()
    steps:
      - name: Block
        if: env.GATE_STATUS == 'FAILED'
        run: |
          echo "test2. Остановка пайплайна из-за критических уязвимостей"
          exit 1      

  test3:
    runs-on: ubuntu-latest    
    needs: test2
    steps:
      - name: test
        run: |
          echo "test3"

