name: test Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest    
    if: always()
    steps:
      - name: step1
        run: |
          echo "test 1"
          echo "GATE_STATUS=FAILED" >> $GITHUB_ENV
      - name: step2
          echo "GATE_STATUS: ${{ env.GATE_STATUS }}"            
